api_key: 'key-6e94a1f4ec7bb48c33ded51b42c953cf'
domain: 'sandbox53081c68140540839915344b642d9919.mailgun.org'
username: 'Default SMTP Login'
password: 'Default Password'
gmail_username: 'username@gmail.com'
gmail_password: 'gmail password'
